### ISSUE TITLE
Maybe re-think hard-coded list of images that require 3D coords

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/openchemistrypy#103]
Currently, there is a hard-coded list of programs that require 3D coords [here](https://github.com/OpenChemistry/openchemistrypy/blob/e6950ef688dc5cd83cb0e95c110fc2079f13e971/openchemistry/_calculation.py#L346-L350). If you try to submit a calculation on a line format molecule with one of those programs, it will automatically generate 3D coords and ask you to submit again. If a program does require 3D coords and it is not on that list, there will probably be unclear errors as to why the calculation failed.

And, as we add more programs that require 3D coords, it may be difficult to remember to append them to that list. For instance, torchani should be on the list currently, but it is not.

Should we maybe make a whitelist instead of programs that do not require 3D coords? Chemml is the only one, currently.

**Comment by cryos** [comment]
I think a whitelist of programs that don't need 3D coordinates is the better way to go - most we deal with will need them, and getting 2D only wrong will generally not lead to errors just much slower performance. I think by virtue of accepting SMILES/InChI we know they don't need 3D coords.

All of them could be made internally cleverer, but I am not sure we want to do that either.

**Comment by alesgenova** [comment]
Agreed that we need to rethink it to some extent.
Also the whole point of implementing the common container interface was done so that users may implement their own images and they would seamlessly work with the platform without us knowing anything about it. The hardcoded blacklist would break this.

**Comment by cryos** [comment]
I don't see major issues with a whitelist for 2D only engines. Ideally if we could register images it could be a part of the JSON/input form where the list is built up as images are added.

**Comment by psavery** [comment]
Yeah, I think this info being a part of the description.json file makes sense. [The current check](https://github.com/OpenChemistry/openchemistrypy/blob/e6950ef688dc5cd83cb0e95c110fc2079f13e971/openchemistry/_calculation.py#L346-L350) occurs on the jupyterlab server computer, which doesn't have access to information about the docker images right now. In the current setup, we might would have to check the description.json on the cluster (in [this file](https://github.com/OpenChemistry/openchemistrypy/blob/master/taskflows/taskflows/__init__.py)). If we do that, it might be able to submit the REST request to generate the 3D coordinates inside the taskflow, wait until it finishes, and then proceed with the calculation.

Or, if we provided the jupyterlab server some information about the docker images (like registering them), the check could be done there.

Whitelist is probably the fastest short-term solution for now.

**Comment by cryos** [comment]
I would prefer whitelist for now, then registering images and having a queryable API to get things like name, versions, needs 2d, 3d, etc.
