### ISSUE TITLE
Celery error when running notebook

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/openchemistrypy#75]
If the master branches of mongochemserver, mongochemdeploy, cumulus, and openchemistrypy are all used, an error occurs when trying to run calculations in the notebook, and the job fails. The error output from celery is attached.

[error.txt](https://github.com/OpenChemistry/openchemistrypy/files/3135698/error.txt)

**Comment by psavery** [comment]
Looks like the error is occuring [here](https://github.com/OpenChemistry/openchemistrypy/blob/d3013811a99f7eafe775250904f46d5a81249c98/taskflows/taskflows/__init__.py#L419), because [_get_job_parameters()](https://github.com/OpenChemistry/openchemistrypy/blob/d3013811a99f7eafe775250904f46d5a81249c98/taskflows/taskflows/__init__.py#L177) is supposed to be passed 4 arguments, but it is only passed 3.

**Comment by cjh1** [comment]
Fixed by #76

**Comment by psavery** [comment]
Issue fixed. Thanks @cjh1!
