### ISSUE TITLE
Ensure that the code version is propagated into the CJSON in the calculation  

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/openchemistrypy#92]
Currently we are writing the code version to the taskflow metadata, we should ensure that this ends up in the calculation, so we can display it in the GUI. We should probably add all the properties returned when we describe the container as this is important meta data.

**Comment by cjh1** [comment]
[This is where](https://github.com/OpenChemistry/openchemistrypy/blob/master/taskflows/taskflows/__init__.py#L337-L341) we write the information to the taskflow at the moment.

**Comment by psavery** [comment]
Here are all of the description properties for the psi4 docker container as an example. Should we put all of these in the taskflow metadata and in the calculation? Or just the program name and version?

```
{
  "name": "PSI4",
  "version": "1.2.1",
  "input": {
    "format": "xyz",
    "parameters": {
      "theory": {
        "type": "string",
        "description": "The theory level: hf | dft",
        "default": "hf"
      },
      "task": {
        "type": "string",
        "description": "The calculation task: energy | optimize | frequencies",
        "default": "energy"
      },
      "basis": {
        "type": "string",
        "description": "The basis set.",
        "default": "cc-pvdz"
      },
      "functional": {
        "type": "string",
        "description": "The XC functional (if ks theory).",
        "default": "b3lyp"
      },
      "charge": {
        "type": "number",
        "description": "The net charge of the system.",
        "default": 0
      },
      "multiplicity": {
        "type": "number",
        "description": "The spin multiplicity.",
        "default": 1
      }
    }
  },
  "output": {
    "format": "cjson"
  }
}
```

**Comment by psavery** [comment]
We decided to leave out the "input" and "output" keys for now. They mostly just show descriptions and defaults for parameters. If needed, we can look these up for a particular calculation using the docker image digest of the calculation.
